# config_wizard_gui.py
import tkinter as tk
from tkinter import messagebox
import requests
from datetime import datetime
import secrets
from cryptography.fernet import Fernet
from pathlib import Path

KEY_FILE = Path('.key')

class ConfigurationWizard(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Fortuna Faucet - Secure Setup Wizard")
        self.geometry("500x350")
        self.configure(bg='#1a1a2e')
        self.resizable(False, False)

        self.api_key = secrets.token_urlsafe(32)
        self.cipher = self._get_cipher()

        self._create_widgets()

    def _get_cipher(self):
        if not KEY_FILE.exists():
            key = Fernet.generate_key()
            with open(KEY_FILE, 'wb') as f:
                f.write(key)
        else:
            with open(KEY_FILE, 'rb') as f:
                key = f.read()
        return Fernet(key)

    def _create_widgets(self):
        # (UI layout remains the same as previous version)
        main_frame = tk.Frame(self, bg='#1a1a2e', padx=20, pady=20)
        main_frame.pack(expand=True, fill=tk.BOTH)
        tk.Label(main_frame, text="Welcome to Fortuna Faucet!", font=('Segoe UI', 16, 'bold'), bg='#1a1a2e', fg='white').pack(pady=(0, 10))
        tk.Label(main_frame, text="Please configure your Betfair API credentials to continue.", font=('Segoe UI', 10), bg='#1a1a2e', fg='#B0B0B0').pack(pady=(0, 25))
        tk.Label(main_frame, text="Betfair App Key:", font=('Segoe UI', 10), bg='#1a1a2e', fg='white').pack(anchor='w')
        self.app_key_entry = tk.Entry(main_frame, width=60, bg='#3C3C3C', fg='white', relief=tk.FLAT)
        self.app_key_entry.pack(pady=5)
        tk.Label(main_frame, text="Betfair Username:", font=('Segoe UI', 10), bg='#1a1a2e', fg='white').pack(anchor='w')
        self.username_entry = tk.Entry(main_frame, width=60, bg='#3C3C3C', fg='white', relief=tk.FLAT)
        self.username_entry.pack(pady=5)
        tk.Label(main_frame, text="Betfair Password:", font=('Segoe UI', 10), bg='#1a1a2e', fg='white').pack(anchor='w')
        self.password_entry = tk.Entry(main_frame, show="*", width=60, bg='#3C3C3C', fg='white', relief=tk.FLAT)
        self.password_entry.pack(pady=5)
        self.save_button = tk.Button(main_frame, text="Verify & Save Securely", font=("Segoe UI", 12, "bold"), bg="#4CAF50", fg="white", relief=tk.FLAT, width=30, command=self.save_config)
        self.save_button.pack(pady=30)

    def save_config(self):
        app_key = self.app_key_entry.get().strip()
        username = self.username_entry.get().strip()
        password = self.password_entry.get().strip()

        if not all([app_key, username, password]):
            messagebox.showerror("Error", "All Betfair fields are required.")
            return

        self.save_button.config(state=tk.DISABLED, text="Verifying...")
        self.update()

        if self._test_betfair_connection(app_key, username, password):
            self._write_env_file(app_key, username, password)
            messagebox.showinfo("Success", "Configuration saved securely! The application will now start.")
            self.destroy()
        else:
            messagebox.showerror("Error", "Betfair connection failed. Please check your credentials.")
            self.save_button.config(state=tk.NORMAL, text="Verify & Save Securely")

    def _test_betfair_connection(self, app_key, username, password):
        # (Same as previous version)
        try:
            auth_url = "https://identitysso.betfair.com/api/login"
            headers = {'X-Application': app_key, 'Content-Type': 'application/x-www-form-urlencoded'}
            payload = f"username={username}&password={password}"
            response = requests.post(auth_url, headers=headers, data=payload, timeout=10)
            return response.json().get('status') == 'SUCCESS'
        except Exception:
            return False

    def _write_env_file(self, app_key, username, password):
        # Encrypt all sensitive values before writing
        encrypted_app_key = f"encrypted:{self.cipher.encrypt(app_key.encode()).decode()}"
        encrypted_username = f"encrypted:{self.cipher.encrypt(username.encode()).decode()}"
        encrypted_password = f"encrypted:{self.cipher.encrypt(password.encode()).decode()}"

        with open('.env', 'w') as f:
            f.write(f"# Fortuna Faucet Environment Configuration (ENCRYPTED)\n")
            f.write(f"# Generated by config_wizard_gui.py on {datetime.now().isoformat()}\n\n")
            f.write(f"API_KEY=\"{self.api_key}\"\n")
            f.write(f"BETFAIR_APP_KEY={encrypted_app_key}\n")
            f.write(f"BETFAIR_USERNAME={encrypted_username}\n")
            f.write(f"BETFAIR_PASSWORD={encrypted_password}\n")

if __name__ == "__main__":
    wizard = ConfigurationWizard()
    wizard.mainloop()