[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "paddock-parser-ng"
version = "1.0.0"
authors = [
  { name="Jules", email="jules@example.com" },
]
description = "A monolithic Python application for parsing and analyzing racecard data."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/example/next-gen"
