# setup_wizard.py
"""
Interactive configuration wizard for Fortuna Faucet.
Guides users through initial setup and API key configuration.
"""

import os
from pathlib import Path
import getpass
import secrets
from datetime import datetime

class SetupWizard:
    def __init__(self):
        self.config = {}
        self.env_file = Path('.env')

    def run(self):
        print("\n" + "="*60)
        print("   Welcome to Fortuna Faucet Setup Wizard")
        print("="*60 + "\n")

        if self.env_file.exists():
            overwrite = input(f"⚠️  Configuration file '{self.env_file}' already exists. Overwrite? (y/N): ").lower()
            if overwrite != 'y':
                print("\nSetup cancelled.")
                return

        print("\n📋 Step 1: Core Configuration")
        print("-" * 60)
        self._configure_core()

        print("\n🔑 Step 2: Betfair API (Required for Live Monitoring)")
        print("-" * 60)
        self._configure_betfair()

        self._write_config()
        self._display_summary()

    def _configure_core(self):
        """Configure essential settings"""
        print("\nGenerating a secure, private API key for communication between your services...")
        api_key = secrets.token_urlsafe(32)
        self.config['API_KEY'] = api_key
        print(f"✅ API Key generated successfully.")

    def _configure_betfair(self):
        """Configure Betfair Exchange API"""
        print("\nBetfair Exchange provides live odds and is essential for the")
        print("LiveOddsMonitor feature. Get your API key at:")
        print("👉 https://docs.developer.betfair.com/display/1smk3cen4v3lu3yomq5qye0ni")

        configure = input("\nConfigure Betfair now? (Y/n): ").lower()
        if configure != 'n':
            self.config['BETFAIR_APP_KEY'] = input("App Key: ").strip()
            self.config['BETFAIR_USERNAME'] = input("Username: ").strip()
            self.config['BETFAIR_PASSWORD'] = getpass.getpass("Password: ").strip()
            print("✅ Betfair configured")
        else:
            self.config['BETFAIR_APP_KEY'] = ""
            self.config['BETFAIR_USERNAME'] = ""
            self.config['BETFAIR_PASSWORD'] = ""
            print("⏭️  Skipped - Live monitoring will be disabled")

    def _write_config(self):
        """Write configuration to .env file"""
        with open(self.env_file, 'w') as f:
            f.write("# Fortuna Faucet Configuration\n")
            f.write(f"# Generated by Setup Wizard on {datetime.now().isoformat()}\n\n")

            f.write("# --- Core Settings ---\n")
            f.write(f"API_KEY=\"{self.config['API_KEY']}\"\n\n")

            f.write("# --- Betfair Exchange ---\n")
            f.write(f"BETFAIR_APP_KEY=\"{self.config['BETFAIR_APP_KEY']}\"\n")
            f.write(f"BETFAIR_USERNAME=\"{self.config['BETFAIR_USERNAME']}\"\n")
            f.write(f"BETFAIR_PASSWORD=\"{self.config['BETFAIR_PASSWORD']}\"\n")

    def _display_summary(self):
        """Display setup summary"""
        print("\n" + "="*60)
        print("   ✅ Setup Complete!")
        print("="*60)
        print(f"\n📁 Configuration saved to '{self.env_file}'")
        print("\n🚀 Next Steps:")
        print("   1. Run INSTALL_FORTUNA.bat (as Administrator) if you haven't already.")
        print("   2. Double-click the 'Launch Fortuna' shortcut on your desktop.")
        print("\n💡 Tip:")
        print("   - You can run this wizard again at any time to reconfigure your settings.")
        print("\n" + "="*60 + "\n")

if __name__ == '__main__':
    wizard = SetupWizard()
    wizard.run()
